/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convert(html: Buffer, options?: ConvertOptions | undefined | null): Promise<ConvertResult>

export declare function convertMany(htmls: Array<Buffer>, options?: ConvertOptions | undefined | null): Promise<ConvertResult[]>

export interface ConvertOptions {
  /** Boilerplate removals learned from a set of pages; applied before conversion. */
  removals?: Removals
  /** CSS selectors whose matching elements are removed before conversion. */
  cssSelectorsToRemove?: Array<string>
  /** CSS selectors that identify the main content root (first match wins). */
  contentSelectors?: Array<string>
  /** Link visible-text patterns whose matching `<a>`/`<button>` elements are removed. */
  linkTextContentToRemove?: Array<string>
  /** Link href prefixes whose matching elements are removed (e.g. `"javascript:"`). */
  linkHrefsToRemove?: Array<string>
  /** `<link rel="...">` tokens to exclude from the extracted `link` map. */
  linkRelTokensToRemove?: Array<string>
  /** When `true`, use text-density scoring to locate the main content element. */
  useTextDensityFilter?: boolean
}

export interface ConvertResult {
  /** Page title from `<title>`. */
  title?: string
  /** `<meta name/property>` map as a plain object. */
  meta: any
  /** `<link rel>` map as a plain object. */
  link: any
  /** Cleaned Markdown content. */
  content: string
  /** Canonical URL from `<link rel="canonical">`. */
  canonicalUrl?: string
  /** Language code from `<html lang="...">`. */
  lang?: string
}

export declare function learn(pages: Array<Buffer>, options?: LearnOptions | undefined | null): Promise<Removals>

export interface LearnOptions {
  /**
   * Text patterns (case-insensitive) that suggest boilerplate content.
   * Pass an empty array to disable pattern matching.
   * Omit (null/undefined) to use the built-in defaults.
   */
  boilerplatePatterns?: Array<string>
  /**
   * Maximum times a selector can match per page before it is considered too broad.
   * Defaults to `20`.
   */
  maxSelectorMatchesPerPage?: number
  /** Minimum average stable-match ratio across all pages. Defaults to `0.6`. */
  minSelectorAverageStableRatio?: number
  /** Minimum per-page stable-match ratio. Defaults to `0.35`. */
  minSelectorPerPageStableRatio?: number
  /** Minimum text length for a snippet to qualify as boilerplate. Defaults to `40`. */
  minSnippetTextLength?: number
  /** Maximum text length for a snippet to qualify as boilerplate. Defaults to `240`. */
  maxSnippetTextLength?: number
}

export interface Removals {
  cssSelectorsToRemove: Array<string>
  htmlToRemove: Array<string>
}
