/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Removals {
  cssSelectorsToRemove: Array<string>
  htmlToRemove: Array<string>
}
export declare function learn(pages: Array<string>): Removals
export declare function convert(html: string, removals?: Removals | undefined | null): string
